// Generated by gencpp from file drempower/tp_msg.msg
// DO NOT EDIT!


#ifndef DREMPOWER_MESSAGE_TP_MSG_H
#define DREMPOWER_MESSAGE_TP_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drempower
{
template <class ContainerAllocator>
struct tp_msg_
{
  typedef tp_msg_<ContainerAllocator> Type;

  tp_msg_()
    : id_list()
    , input_pos_list()
    , interpolation_freq_list()  {
    }
  tp_msg_(const ContainerAllocator& _alloc)
    : id_list(_alloc)
    , input_pos_list(_alloc)
    , interpolation_freq_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _id_list_type;
  _id_list_type id_list;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _input_pos_list_type;
  _input_pos_list_type input_pos_list;

   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _interpolation_freq_list_type;
  _interpolation_freq_list_type interpolation_freq_list;





  typedef boost::shared_ptr< ::drempower::tp_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drempower::tp_msg_<ContainerAllocator> const> ConstPtr;

}; // struct tp_msg_

typedef ::drempower::tp_msg_<std::allocator<void> > tp_msg;

typedef boost::shared_ptr< ::drempower::tp_msg > tp_msgPtr;
typedef boost::shared_ptr< ::drempower::tp_msg const> tp_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drempower::tp_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drempower::tp_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drempower::tp_msg_<ContainerAllocator1> & lhs, const ::drempower::tp_msg_<ContainerAllocator2> & rhs)
{
  return lhs.id_list == rhs.id_list &&
    lhs.input_pos_list == rhs.input_pos_list &&
    lhs.interpolation_freq_list == rhs.interpolation_freq_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drempower::tp_msg_<ContainerAllocator1> & lhs, const ::drempower::tp_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drempower

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drempower::tp_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drempower::tp_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drempower::tp_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drempower::tp_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drempower::tp_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drempower::tp_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drempower::tp_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6424aefc0d5f032d0edf23b2502a77f";
  }

  static const char* value(const ::drempower::tp_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6424aefc0d5f032ULL;
  static const uint64_t static_value2 = 0xd0edf23b2502a77fULL;
};

template<class ContainerAllocator>
struct DataType< ::drempower::tp_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drempower/tp_msg";
  }

  static const char* value(const ::drempower::tp_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drempower::tp_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] id_list\n"
"float32[] input_pos_list\n"
"uint16[] interpolation_freq_list\n"
;
  }

  static const char* value(const ::drempower::tp_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drempower::tp_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id_list);
      stream.next(m.input_pos_list);
      stream.next(m.interpolation_freq_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tp_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drempower::tp_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drempower::tp_msg_<ContainerAllocator>& v)
  {
    s << indent << "id_list[]" << std::endl;
    for (size_t i = 0; i < v.id_list.size(); ++i)
    {
      s << indent << "  id_list[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.id_list[i]);
    }
    s << indent << "input_pos_list[]" << std::endl;
    for (size_t i = 0; i < v.input_pos_list.size(); ++i)
    {
      s << indent << "  input_pos_list[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.input_pos_list[i]);
    }
    s << indent << "interpolation_freq_list[]" << std::endl;
    for (size_t i = 0; i < v.interpolation_freq_list.size(); ++i)
    {
      s << indent << "  interpolation_freq_list[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.interpolation_freq_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DREMPOWER_MESSAGE_TP_MSG_H
