// Generated by gencpp from file drempower/ip_msg.msg
// DO NOT EDIT!


#ifndef DREMPOWER_MESSAGE_IP_MSG_H
#define DREMPOWER_MESSAGE_IP_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drempower
{
template <class ContainerAllocator>
struct ip_msg_
{
  typedef ip_msg_<ContainerAllocator> Type;

  ip_msg_()
    : id_list()
    , input_pos_list()
    , input_vel_list()
    , input_torque_list()
    , impedance_kp_list()
    , impedance_kd_list()  {
    }
  ip_msg_(const ContainerAllocator& _alloc)
    : id_list(_alloc)
    , input_pos_list(_alloc)
    , input_vel_list(_alloc)
    , input_torque_list(_alloc)
    , impedance_kp_list(_alloc)
    , impedance_kd_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _id_list_type;
  _id_list_type id_list;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _input_pos_list_type;
  _input_pos_list_type input_pos_list;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _input_vel_list_type;
  _input_vel_list_type input_vel_list;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _input_torque_list_type;
  _input_torque_list_type input_torque_list;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _impedance_kp_list_type;
  _impedance_kp_list_type impedance_kp_list;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _impedance_kd_list_type;
  _impedance_kd_list_type impedance_kd_list;





  typedef boost::shared_ptr< ::drempower::ip_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drempower::ip_msg_<ContainerAllocator> const> ConstPtr;

}; // struct ip_msg_

typedef ::drempower::ip_msg_<std::allocator<void> > ip_msg;

typedef boost::shared_ptr< ::drempower::ip_msg > ip_msgPtr;
typedef boost::shared_ptr< ::drempower::ip_msg const> ip_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drempower::ip_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drempower::ip_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drempower::ip_msg_<ContainerAllocator1> & lhs, const ::drempower::ip_msg_<ContainerAllocator2> & rhs)
{
  return lhs.id_list == rhs.id_list &&
    lhs.input_pos_list == rhs.input_pos_list &&
    lhs.input_vel_list == rhs.input_vel_list &&
    lhs.input_torque_list == rhs.input_torque_list &&
    lhs.impedance_kp_list == rhs.impedance_kp_list &&
    lhs.impedance_kd_list == rhs.impedance_kd_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drempower::ip_msg_<ContainerAllocator1> & lhs, const ::drempower::ip_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drempower

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drempower::ip_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drempower::ip_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drempower::ip_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drempower::ip_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drempower::ip_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drempower::ip_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drempower::ip_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de54906fb10af526c02f64da7a46b9d0";
  }

  static const char* value(const ::drempower::ip_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde54906fb10af526ULL;
  static const uint64_t static_value2 = 0xc02f64da7a46b9d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::drempower::ip_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drempower/ip_msg";
  }

  static const char* value(const ::drempower::ip_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drempower::ip_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] id_list\n"
"float32[] input_pos_list\n"
"float32[] input_vel_list\n"
"float32[] input_torque_list\n"
"float32[] impedance_kp_list\n"
"float32[] impedance_kd_list\n"
;
  }

  static const char* value(const ::drempower::ip_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drempower::ip_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id_list);
      stream.next(m.input_pos_list);
      stream.next(m.input_vel_list);
      stream.next(m.input_torque_list);
      stream.next(m.impedance_kp_list);
      stream.next(m.impedance_kd_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ip_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drempower::ip_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drempower::ip_msg_<ContainerAllocator>& v)
  {
    s << indent << "id_list[]" << std::endl;
    for (size_t i = 0; i < v.id_list.size(); ++i)
    {
      s << indent << "  id_list[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.id_list[i]);
    }
    s << indent << "input_pos_list[]" << std::endl;
    for (size_t i = 0; i < v.input_pos_list.size(); ++i)
    {
      s << indent << "  input_pos_list[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.input_pos_list[i]);
    }
    s << indent << "input_vel_list[]" << std::endl;
    for (size_t i = 0; i < v.input_vel_list.size(); ++i)
    {
      s << indent << "  input_vel_list[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.input_vel_list[i]);
    }
    s << indent << "input_torque_list[]" << std::endl;
    for (size_t i = 0; i < v.input_torque_list.size(); ++i)
    {
      s << indent << "  input_torque_list[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.input_torque_list[i]);
    }
    s << indent << "impedance_kp_list[]" << std::endl;
    for (size_t i = 0; i < v.impedance_kp_list.size(); ++i)
    {
      s << indent << "  impedance_kp_list[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.impedance_kp_list[i]);
    }
    s << indent << "impedance_kd_list[]" << std::endl;
    for (size_t i = 0; i < v.impedance_kd_list.size(); ++i)
    {
      s << indent << "  impedance_kd_list[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.impedance_kd_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DREMPOWER_MESSAGE_IP_MSG_H
