// Generated by gencpp from file drempower/pp_msg.msg
// DO NOT EDIT!


#ifndef DREMPOWER_MESSAGE_PP_MSG_H
#define DREMPOWER_MESSAGE_PP_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drempower
{
template <class ContainerAllocator>
struct pp_msg_
{
  typedef pp_msg_<ContainerAllocator> Type;

  pp_msg_()
    : id_list()
    , input_pos_list()
    , tt_vel_limit_list()
    , tt_accel_limit_list()
    , tt_decel_limit_list()  {
    }
  pp_msg_(const ContainerAllocator& _alloc)
    : id_list(_alloc)
    , input_pos_list(_alloc)
    , tt_vel_limit_list(_alloc)
    , tt_accel_limit_list(_alloc)
    , tt_decel_limit_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint16_t>> _id_list_type;
  _id_list_type id_list;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _input_pos_list_type;
  _input_pos_list_type input_pos_list;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tt_vel_limit_list_type;
  _tt_vel_limit_list_type tt_vel_limit_list;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tt_accel_limit_list_type;
  _tt_accel_limit_list_type tt_accel_limit_list;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tt_decel_limit_list_type;
  _tt_decel_limit_list_type tt_decel_limit_list;





  typedef boost::shared_ptr< ::drempower::pp_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drempower::pp_msg_<ContainerAllocator> const> ConstPtr;

}; // struct pp_msg_

typedef ::drempower::pp_msg_<std::allocator<void> > pp_msg;

typedef boost::shared_ptr< ::drempower::pp_msg > pp_msgPtr;
typedef boost::shared_ptr< ::drempower::pp_msg const> pp_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drempower::pp_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drempower::pp_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drempower::pp_msg_<ContainerAllocator1> & lhs, const ::drempower::pp_msg_<ContainerAllocator2> & rhs)
{
  return lhs.id_list == rhs.id_list &&
    lhs.input_pos_list == rhs.input_pos_list &&
    lhs.tt_vel_limit_list == rhs.tt_vel_limit_list &&
    lhs.tt_accel_limit_list == rhs.tt_accel_limit_list &&
    lhs.tt_decel_limit_list == rhs.tt_decel_limit_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drempower::pp_msg_<ContainerAllocator1> & lhs, const ::drempower::pp_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drempower

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drempower::pp_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drempower::pp_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drempower::pp_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drempower::pp_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drempower::pp_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drempower::pp_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drempower::pp_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c8302ac9be2cb472f38f4465fbbc73c";
  }

  static const char* value(const ::drempower::pp_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c8302ac9be2cb47ULL;
  static const uint64_t static_value2 = 0x2f38f4465fbbc73cULL;
};

template<class ContainerAllocator>
struct DataType< ::drempower::pp_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drempower/pp_msg";
  }

  static const char* value(const ::drempower::pp_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drempower::pp_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[] id_list\n"
"float32[] input_pos_list\n"
"float32[] tt_vel_limit_list\n"
"float32[] tt_accel_limit_list\n"
"float32[] tt_decel_limit_list\n"
;
  }

  static const char* value(const ::drempower::pp_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drempower::pp_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id_list);
      stream.next(m.input_pos_list);
      stream.next(m.tt_vel_limit_list);
      stream.next(m.tt_accel_limit_list);
      stream.next(m.tt_decel_limit_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pp_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drempower::pp_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drempower::pp_msg_<ContainerAllocator>& v)
  {
    s << indent << "id_list[]" << std::endl;
    for (size_t i = 0; i < v.id_list.size(); ++i)
    {
      s << indent << "  id_list[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.id_list[i]);
    }
    s << indent << "input_pos_list[]" << std::endl;
    for (size_t i = 0; i < v.input_pos_list.size(); ++i)
    {
      s << indent << "  input_pos_list[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.input_pos_list[i]);
    }
    s << indent << "tt_vel_limit_list[]" << std::endl;
    for (size_t i = 0; i < v.tt_vel_limit_list.size(); ++i)
    {
      s << indent << "  tt_vel_limit_list[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tt_vel_limit_list[i]);
    }
    s << indent << "tt_accel_limit_list[]" << std::endl;
    for (size_t i = 0; i < v.tt_accel_limit_list.size(); ++i)
    {
      s << indent << "  tt_accel_limit_list[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tt_accel_limit_list[i]);
    }
    s << indent << "tt_decel_limit_list[]" << std::endl;
    for (size_t i = 0; i < v.tt_decel_limit_list.size(); ++i)
    {
      s << indent << "  tt_decel_limit_list[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tt_decel_limit_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DREMPOWER_MESSAGE_PP_MSG_H
