// Generated by gencpp from file drempower/state_msg.msg
// DO NOT EDIT!


#ifndef DREMPOWER_MESSAGE_STATE_MSG_H
#define DREMPOWER_MESSAGE_STATE_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drempower
{
template <class ContainerAllocator>
struct state_msg_
{
  typedef state_msg_<ContainerAllocator> Type;

  state_msg_()
    : id(0)
    , pos_estimate(0.0)
    , vel_estimate(0.0)
    , torque_estimate(0.0)
    , traj_done(false)
    , axis_error(false)  {
    }
  state_msg_(const ContainerAllocator& _alloc)
    : id(0)
    , pos_estimate(0.0)
    , vel_estimate(0.0)
    , torque_estimate(0.0)
    , traj_done(false)
    , axis_error(false)  {
  (void)_alloc;
    }



   typedef uint16_t _id_type;
  _id_type id;

   typedef float _pos_estimate_type;
  _pos_estimate_type pos_estimate;

   typedef float _vel_estimate_type;
  _vel_estimate_type vel_estimate;

   typedef float _torque_estimate_type;
  _torque_estimate_type torque_estimate;

   typedef uint8_t _traj_done_type;
  _traj_done_type traj_done;

   typedef uint8_t _axis_error_type;
  _axis_error_type axis_error;





  typedef boost::shared_ptr< ::drempower::state_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drempower::state_msg_<ContainerAllocator> const> ConstPtr;

}; // struct state_msg_

typedef ::drempower::state_msg_<std::allocator<void> > state_msg;

typedef boost::shared_ptr< ::drempower::state_msg > state_msgPtr;
typedef boost::shared_ptr< ::drempower::state_msg const> state_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drempower::state_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drempower::state_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drempower::state_msg_<ContainerAllocator1> & lhs, const ::drempower::state_msg_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pos_estimate == rhs.pos_estimate &&
    lhs.vel_estimate == rhs.vel_estimate &&
    lhs.torque_estimate == rhs.torque_estimate &&
    lhs.traj_done == rhs.traj_done &&
    lhs.axis_error == rhs.axis_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drempower::state_msg_<ContainerAllocator1> & lhs, const ::drempower::state_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drempower

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drempower::state_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drempower::state_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drempower::state_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drempower::state_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drempower::state_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drempower::state_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drempower::state_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5e607e2332f726698096f3c92a391b0";
  }

  static const char* value(const ::drempower::state_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5e607e2332f7266ULL;
  static const uint64_t static_value2 = 0x98096f3c92a391b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::drempower::state_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drempower/state_msg";
  }

  static const char* value(const ::drempower::state_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drempower::state_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 id\n"
"float32 pos_estimate\n"
"float32 vel_estimate\n"
"float32  torque_estimate\n"
"bool   traj_done\n"
"bool   axis_error\n"
;
  }

  static const char* value(const ::drempower::state_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drempower::state_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pos_estimate);
      stream.next(m.vel_estimate);
      stream.next(m.torque_estimate);
      stream.next(m.traj_done);
      stream.next(m.axis_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct state_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drempower::state_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drempower::state_msg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.id);
    s << indent << "pos_estimate: ";
    Printer<float>::stream(s, indent + "  ", v.pos_estimate);
    s << indent << "vel_estimate: ";
    Printer<float>::stream(s, indent + "  ", v.vel_estimate);
    s << indent << "torque_estimate: ";
    Printer<float>::stream(s, indent + "  ", v.torque_estimate);
    s << indent << "traj_done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.traj_done);
    s << indent << "axis_error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.axis_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DREMPOWER_MESSAGE_STATE_MSG_H
